url: https://varshaprabhakar07.github.io
baseurl: /VarshaPrabhakar07.github.io/

# Site settings
title: Varsha Prabhakar
email: varshaprabhakar07@gmail.com
description: "Varsha Prabhakar Personal Blog"


# Team names, titles and social links
# people:
# - name: Kay Garland
#   pic: 1
#   position: Lead Designer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: stack-overflow
#       url: #

# - name: Larry Parker
#   pic: 2
#   position: Lead Marketer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: linkedin
#       url: #

# - name: Diana Petersen
#   pic: 3
#   position: Lead Developer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: google-plus
#       url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/Varsha_P07
  # - title: facebook
  #   url:
  - title: linkedIn
    url: https://linkedin.com/varshaprabhakar07
  - title: github
    url: https://github.com/VarshaPrabhakar07
  - title: tableau
    url: https://public.tableau.com/profile/varsha.prabhakar#!/

# Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty